
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo4j?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
